### ISSUE TITLE
MultivaluedMapEntityProvider fail in case the request inputStream has already been consumed

### ISSUE THREAD

**Issue by Panthro** [codenvy/everrest#7]
Given:
https://github.com/codenvy/everrest/blob/master/everrest-core/src/main/java/org/everrest/core/impl/provider/MultivaluedMapEntityProvider.java#L75

For instance if you have a filter that calls `request.getParameter("paramName")` before in the filter chain the Provider will fail to map any POST parameter as the input stream is already consumed and any `read()` call will return `-1`.

The Provider should take it into account and add the `request.getParameterMap()` to its results.

**Comment by skabashnyuk** [comment]
What do you propose to take  into account?

**Comment by Panthro** [comment]
From the `EnvironmentContext` you can get the request, and add all the `request.getParam()` to the map returning map.

**Comment by skabashnyuk** [comment]
done in ed624e9db41989191acaa025530514f464a4c79b
